/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    places: Place;
    comments: Comment;
    'post-likes': PostLike;
    follows: Follow;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    places: PlacesSelect<false> | PlacesSelect<true>;
    comments: CommentsSelect<false> | CommentsSelect<true>;
    'post-likes': PostLikesSelect<false> | PostLikesSelect<true>;
    follows: FollowsSelect<false> | FollowsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  profileImage?: (string | null) | Media;
  firstName: string;
  lastName: string;
  district:
    | 'Ampara'
    | 'Anuradhapura'
    | 'Badulla'
    | 'Batticaloa'
    | 'Colombo'
    | 'Galle'
    | 'Gampaha'
    | 'Hambantota'
    | 'Jaffna'
    | 'Kalutara'
    | 'Kandy'
    | 'Kegalle'
    | 'Kilinochchi'
    | 'Kurunegala'
    | 'Mannar'
    | 'Matale'
    | 'Matara'
    | 'Monaragala'
    | 'Mullaitivu'
    | 'Nuwara Eliya'
    | 'Polonnaruwa'
    | 'Puttalam'
    | 'Ratnapura'
    | 'Trincomalee'
    | 'Vavuniya';
  roles: ('admin' | 'user')[];
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Community-submitted hidden places across Sri Lanka. Review and approve/reject submissions.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "places".
 */
export interface Place {
  id: string;
  /**
   * Name of the hidden place.
   */
  title: string;
  /**
   * What makes this place special.
   */
  description: string;
  locationType:
    | 'waterfall'
    | 'beach'
    | 'forest'
    | 'ruins'
    | 'viewpoint'
    | 'cave'
    | 'river'
    | 'wildlife'
    | 'village'
    | 'other';
  entryFee?: ('free' | 'small' | 'moderate' | 'high' | 'unknown') | null;
  /**
   * District where the place is located.
   */
  district:
    | 'Ampara'
    | 'Anuradhapura'
    | 'Badulla'
    | 'Batticaloa'
    | 'Colombo'
    | 'Galle'
    | 'Gampaha'
    | 'Hambantota'
    | 'Jaffna'
    | 'Kalutara'
    | 'Kandy'
    | 'Kegalle'
    | 'Kilinochchi'
    | 'Kurunegala'
    | 'Mannar'
    | 'Matale'
    | 'Matara'
    | 'Monaragala'
    | 'Mullaitivu'
    | 'Nuwara Eliya'
    | 'Polonnaruwa'
    | 'Puttalam'
    | 'Ratnapura'
    | 'Trincomalee'
    | 'Vavuniya';
  /**
   * Nearest city, town or village.
   */
  city?: string | null;
  /**
   * Raw Cloudinary data — use Media Preview above to view images/videos.
   */
  mediaFiles?:
    | {
        url: string;
        publicId: string;
        resourceType: 'image' | 'video';
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Automatically set to the logged-in user who submitted this place.
   */
  submittedBy?: (string | null) | User;
  /**
   * Set by admin after reviewing the submission.
   */
  status: 'pending' | 'approved' | 'rejected';
  /**
   * Shown to the submitter — explain why it was approved or rejected.
   */
  adminNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * User comments on approved places.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comments".
 */
export interface Comment {
  id: string;
  /**
   * The place this comment belongs to.
   */
  place: string | Place;
  /**
   * Set when this is a reply to another comment.
   */
  parentComment?: (string | null) | Comment;
  /**
   * Automatically set to the logged-in user.
   */
  author: string | User;
  /**
   * The comment text.
   */
  text: string;
  likes?: number | null;
  likedBy?: (string | User)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * One record per user-post like.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "post-likes".
 */
export interface PostLike {
  id: string;
  place: string | Place;
  user: string | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * One record per follower → following relationship.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "follows".
 */
export interface Follow {
  id: string;
  follower: string | User;
  following: string | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'places';
        value: string | Place;
      } | null)
    | ({
        relationTo: 'comments';
        value: string | Comment;
      } | null)
    | ({
        relationTo: 'post-likes';
        value: string | PostLike;
      } | null)
    | ({
        relationTo: 'follows';
        value: string | Follow;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  profileImage?: T;
  firstName?: T;
  lastName?: T;
  district?: T;
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "places_select".
 */
export interface PlacesSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  locationType?: T;
  entryFee?: T;
  district?: T;
  city?: T;
  mediaFiles?:
    | T
    | {
        url?: T;
        publicId?: T;
        resourceType?: T;
        caption?: T;
        id?: T;
      };
  submittedBy?: T;
  status?: T;
  adminNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comments_select".
 */
export interface CommentsSelect<T extends boolean = true> {
  place?: T;
  parentComment?: T;
  author?: T;
  text?: T;
  likes?: T;
  likedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "post-likes_select".
 */
export interface PostLikesSelect<T extends boolean = true> {
  place?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "follows_select".
 */
export interface FollowsSelect<T extends boolean = true> {
  follower?: T;
  following?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}